version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: taphoa_mmo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taphoa_mmo
    ports:
      - "3301:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
